apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: europe-docker.pkg.dev/thumbnail-app-acs-2025/thumbnail-repo/storage-service:V7
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: gcp-key
          mountPath: "/usr/src/app/thumbnail-app-acs-2025-3b06f94a8f55.json"
          subPath: thumbnail-app-acs-2025-3b06f94a8f55.json
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: gcp-key
        secret:
          secretName: gcs-sa-key
