apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: europe-docker.pkg.dev/thumbnail-app-acs-2025/thumbnail-repo/storage-service
        ports:
        - containerPort: 3003
