apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: europe-docker.pkg.dev/thumbnail-app-acs-2025/thumbnail-repo/upload-service:V5
        ports:
        - containerPort: 3001
        env:
        - name: THUMBNAIL_SERVICE_URL
          value: "http://thumbnail-service:80/process"
