service: thumbnail-service
runtime: custom
env: flex

env_variables:
  STORAGE_SERVICE_URL: https://storage-service-dot-thumbnail-app-acs-2025.ey.r.appspot.com/store

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
