runtime: nodejs
env: flex
entrypoint: node index.js

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

service: storage-service
